import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:provider_start/core/constant/view_routes.dart';
import 'package:provider_start/core/enums/tab_view.dart';
import 'package:provider_start/ui/views/tab_container.dart';

/// Class that generates routes for the application
///   - Routes are generated by the list of routes in the app
///   - Routes can also require paramaters. e.g. `PostDetailView(post: post)`
class Router {
  static Route<dynamic> generateRoute(RouteSettings settings, bool isAndroid) {
    if (isAndroid)
      return MaterialPageRoute(
        settings: RouteSettings(name: settings.name),
        builder: (context) => _generateView(settings),
        fullscreenDialog: _fullScreenDialogs.contains(settings.name),
      );
    else
      return CupertinoPageRoute(
        settings: RouteSettings(name: settings.name),
        builder: (context) => _generateView(settings),
        fullscreenDialog: _fullScreenDialogs.contains(settings.name),
      );
  }

  static Widget _generateView(RouteSettings settings) {
    switch (settings.name) {

      // Tab Views
      case ViewRoutes.tab_container:
        final view = settings.arguments as TabView;
        return TabContainer(view: view);

      default:
        return Scaffold(
          body: Center(
            child: Text('No route defined for ${settings.name}'),
          ),
        );
    }
  }

  // Add routes that should behave as fullScreenDialogs
  static final _fullScreenDialogs = [
    // Routes.route_1,
    // Routes.route_2,
  ];
}
