import 'package:flutter/material.dart';
import 'package:provider_start/core/constant/routes.dart';
import 'package:provider_start/core/enums/tab_view.dart';
import 'package:provider_start/ui/views/tab_container.dart';

/// Class that generates routes for the application
///   - Routes are generated by the list of routes in the app
///   - Routes can also require paramaters. e.g. `PostDetailView(post: post)`
class Router {
  static Route<dynamic> generateRoute(RouteSettings settings) {
    switch (settings.name) {

      // Tab Views
      case Routes.tab_container:
        var view = settings.arguments as TabView;
        return MaterialPageRoute(builder: (_) => TabContainer(view: view));

      default:
        return MaterialPageRoute(
          builder: (_) => Scaffold(
            body: Center(
              child: Text('No route defined for ${settings.name}'),
            ),
          ),
        );
    }
  }
}
